name: Update README with current date

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update README with current date
        run: |
          sed -i "s/DATE/$(date +%Y-%m-%d)/g" README.md
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Update README with current date"
          git push
