on:
  schedule:
    - cron: '0 0 * * *' # 运行一次每天午夜
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Set date
      run: |
        echo "DATE=$(date +'%Y-%m-%d')" >> $(date $GITHUB_ENV
        
    - name: Update README
      run: |
        sed -i "s/[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}/$(date $$DATE/g" README.md
        
    - name: Commit and push if it changed 
      run : |
        git diff
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Action"
        git commit -am "Update date in README" && echo ::set-output name=status::success || echo ::set-output name=status::skipped 
        if [ $(date $$$(steps.commit.outputs.status) == "success" ]
          then 
            git push  
          fi  

